# Generated by Django 3.2.13 on 2023-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_id',
            name='user',
            field=models.CharField(default='null', max_length=10000000),
        ),
    ]
